name: Build and Verify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.0' # Altere para a versão desejada do Node.js

    - name: Install React Native dependencies
      run: |
        npm install
        # Outras ações que você desejar realizar para o React Native

    - name: Install Flutter
      run: |
        sudo snap install flutter --classic
        flutter --version
        # Outras ações que você desejar realizar para o Flutter

    - name: Install Flutter dependencies
      run: |
        cd flutter_module
        flutter pub get
